### ISSUE TITLE
Make use of Docker build cache

### ISSUE THREAD

**Issue by nyxkrage** [stuck-overflow/ferris-bot#62]
Right now, as soon as any code is changed the Docker will rebuild the entire project including dependcies, this is a waste and if we structure the dockerfile correctly, this additional work can easily be avoided.
It requires copying the Cargo.toml and Cargo.lock to the builder, and building an empty project for release, this and then copying the source code and rebuilding

**Comment by nyxkrage** [comment]
In the following dockerfile you can see build twice(build and install).
```docker
# Dockerfile for creating a statically-linked Rust application using docker's
# multi-stage build feature. This also leverages the docker build cache to avoid
# re-downloading dependencies if they have not changed.
FROM rust:1.51 AS build
WORKDIR /usr/src

# Download the target for static linking.
RUN rustup target add x86_64-unknown-linux-musl

# Create a dummy project and build the app's dependencies.
# If the Cargo.toml or Cargo.lock files have not changed,
# we can use the docker build cache and skip these (typically slow) steps.
RUN USER=root cargo new APP-NAME
WORKDIR /usr/src/APP-NAME
COPY Cargo.toml Cargo.lock ./
RUN cargo build --release

# Copy the source and build the application.
COPY src ./src
RUN cargo install --target x86_64-unknown-linux-musl --path .

# Copy the statically-linked binary into a scratch container.
FROM scratch
COPY --from=build /usr/local/cargo/bin/APP-NAME .
USER 1000
CMD ["./APP-NAME"]
```

**Comment by satu** [comment]
I verified that if I used `docker-compose up` with a `docker-compose.yml` file containing `build: .` instead of `image: stuckoverflow/ferrisbot:latest` the image is built the first time I invoke `up`. Now if I change something in `src/main.rs` and re-invoke `docker-compose up`, the cached image is used anyway.

Similarly, if I run `docker build .` an image is built as expected. If I change something in `src/main.rs` and invoke `docker build .` again, all the steps need to be cached.

In light of this, I'd like to understand better the mechanics involved and how to have docker behaving smartly here so that it can be used for development.

I care a bit less about the build speed for releasing. The whole build takes 5 mins but we are not yet integrated in a continuous build so optimisations in this space are a bit premature.

**Comment by rexroof** [comment]
I often argue the opposite!   it's better to have optimizations for development, considering CI/CD is often run in an automated fashion and humans aren't actively waiting on it.    I'm happy to walk you through how it works, I've given a few talks on docker image optimizations. 
(not the rust specifics, thats outside of my wheelhouse)

**Comment by satu** [comment]
I think we're saying the same thing? :) What I meant is that if this optimisation can benefit development iterations then I really want to find a way to have it.

Do you happen to know how I can convince docker to smartly rebuild instead of using the cache only in case a file is changed?

If you want to try it yourself you don't even need rust installed. Check out the repo and run `docker build .`, then change a println in src/main.rs and run `docker build .`. What happens is that the second build is effectively a no-op, while I would expect Docker to be smart and re-do the build.
